# Generated by Django 5.1.6 on 2025-03-11 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_Laws',
            fields=[
                ('Law_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Law_Title', models.CharField(max_length=60)),
                ('Law_Category', models.CharField(max_length=25)),
                ('Law_Relevant', models.CharField(max_length=255)),
                ('Law_Punishment', models.TextField()),
                ('Law_Description', models.TextField()),
                ('Law_link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Basic_Laws',
            },
        ),
        migrations.CreateModel(
            name='Book_Lawyer',
            fields=[
                ('Book_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Lawyer_Name', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=25)),
                ('Appointment_Date', models.DateField()),
                ('Appointment_Time', models.CharField(max_length=100)),
                ('Contact_Time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Book_Lawyer',
            },
        ),
        migrations.CreateModel(
            name='Emergency_Numbers',
            fields=[
                ('Num_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Emergency_Numbers',
            },
        ),
        migrations.CreateModel(
            name='Lawyer_Register',
            fields=[
                ('Lawyer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=20)),
                ('Experience', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Firm', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='media/')),
                ('Price', models.IntegerField()),
            ],
            options={
                'db_table': 'Lawyer_Register',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Number', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Payment_Details',
            fields=[
                ('Pay_Id', models.AutoField(primary_key=True, serialize=False)),
                ('CardName', models.CharField(max_length=100)),
                ('CardNumber', models.CharField(max_length=30)),
                ('CardExpiryMonth', models.CharField(max_length=10)),
                ('CardExpiryYear', models.CharField(max_length=4)),
                ('Cvv', models.CharField(max_length=4)),
                ('Price', models.IntegerField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.book_lawyer')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
            options={
                'db_table': 'Payment_Details',
            },
        ),
        migrations.AddField(
            model_name='book_lawyer',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register'),
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('Case_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Number', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
        migrations.CreateModel(
            name='Case_Details',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_Type', models.CharField(max_length=100)),
                ('Complaint_Subject', models.CharField(max_length=255)),
                ('Complaint_Area', models.CharField(max_length=100)),
                ('Complaint_Date', models.DateField()),
                ('Complaint_Details', models.TextField()),
                ('Complaint_Image', models.ImageField(upload_to='media/')),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_details')),
            ],
            options={
                'db_table': 'CaseDetails',
            },
        ),
    ]
