# Generated by Django 5.1.6 on 2025-03-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basic_laws',
            table='BasicLaws',
        ),
    ]
