# Generated by Django 5.1.6 on 2025-03-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_basic_laws_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basic_laws',
            table='Basic_Laws',
        ),
        migrations.AlterModelTable(
            name='case_details',
            table='Case_Details',
        ),
    ]
