# Generated by Django 5.1.6 on 2025-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_basic_laws_table_alter_case_details_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_lawyer',
            name='District',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='user_details',
            name='District',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
